### ISSUE TITLE
1.1版本bug

### ISSUE THREAD

**Issue by TCDTH** [roomanl/AndroidDownload#1]
1.第一次下载到百分之百有下载速度显示，但是一直等了很久都还在下载，第二次下载，下载到百分之百，然后出来感叹号显示下载失败
2.种子不能选择想下载的项

**Comment by yuger** [comment]
随便搜个什么关键词，比如搜索“啊”，然后全部是那种内容。

App反应有点慢，又不像是卡顿

**Comment by roomanl** [comment]
> 随便搜个什么关键词，比如搜索“啊”，然后全部是那种内容。
> 
> App反应有点慢，又不像是卡顿

搜索结果都是来自第三方网站的结果。卡顿慢慢优化就好了，初始版本肯定存在很多问题

**Comment by yuger** [comment]
> > 随便搜个什么关键词，比如搜索“啊”，然后全部是那种内容。
> > App反应有点慢，又不像是卡顿
> 
> 搜索结果都是来自第三方网站的结果。卡顿慢慢优化就好了，初始版本肯定存在很多问题

不错，已star，回头我也编译一个玩玩，有同步最新代码没？
